name: General Feedback
description: Share suggestions, feedback, or ideas for the Fidakune project
title: '[FEEDBACK] '
labels: ['feedback', 'community-input']
body:
  - type: dropdown
    id: feedback-type
    attributes:
      label: Feedback Type
      description: What type of feedback are you providing?
      options:
        - Language Design
        - Documentation
        - Accessibility
        - Cultural Sensitivity
        - Learning Materials
        - Community Process
        - Website/Tools
        - Other
    validations:
      required: true
  
  - type: textarea
    id: feedback
    attributes:
      label: Your Feedback
      description: Please share your thoughts, suggestions, or observations
      placeholder: Describe your feedback here...
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Your linguistic background, experience with constructed languages, or relevant expertise
      placeholder: e.g., "Native Mandarin speaker", "ESL teacher", "Accessibility advocate"
    validations:
      required: false
  
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: If you have specific suggestions for improvement, please share them
      placeholder: Optional - What would you like to see changed or improved?
    validations:
      required: false
