name: Vocabulary Proposal
description: Propose a new word for Fidakune
title: '[VOCAB PROPOSAL] '
labels: ['vocab-proposal', 'community-input']
body:
  - type: input
    id: word
    attributes:
      label: Proposed Word
      description: The word you're proposing (e.g., `luna`)
      placeholder: luna
    validations:
      required: true
  
  - type: input
    id: pronunciation
    attributes:
      label: Pronunciation (IPA)
      description: How the word should be pronounced using IPA notation
      placeholder: /Ëˆlu.na/
    validations:
      required: true
  
  - type: input
    id: meaning
    attributes:
      label: Meaning
      description: What the word means in English
      placeholder: moon
    validations:
      required: true
  
  - type: dropdown
    id: domain
    attributes:
      label: Semantic Domain
      description: Which category does this word belong to?
      options:
        - Nature
        - Society
        - Emotion
        - Technology
        - Grammar
        - Cognition
        - Body
        - Time
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: word-type
    attributes:
      label: Word Type
      description: What type of word is this?
      options:
        - noun
        - verb
        - adjective
        - adverb
        - particle
        - pronoun
        - conjunction
        - other
    validations:
      required: true
  
  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Why is this word needed? How does it fit Fidakune's design principles?
      placeholder: This word is needed for basic communication about astronomy and time. It follows the phonotactic rules (CV.CV structure) and doesn't conflict with existing vocabulary.
    validations:
      required: true
  
  - type: textarea
    id: cultural-notes
    attributes:
      label: Cultural Considerations
      description: Any cultural sensitivity considerations for this word?
      placeholder: Optional - Note any cultural considerations or alternative meanings in different cultures
    validations:
      required: false
  
  - type: checkboxes
    id: compliance
    attributes:
      label: Compliance Checklist
      description: Please confirm your proposal meets these requirements
      options:
        - label: The word follows Fidakune's phonotactic rules (Section 4.2)
          required: true
        - label: The word doesn't conflict with existing vocabulary
          required: true
        - label: The word supports cultural neutrality goals
          required: true
